name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Bun 🚀
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies 🔧
        run: bun install --frozen-lockfile

      - name: Update site URL 📝
        run: |
          sed -i 's|site:.*|site: "https://ajmalbuv.github.io",|' astro.config.mjs

      - name: Build 🏗️
        run: bun run build
        env:
          PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
          PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          single-commit: true
